apiVersion: v2
name: system-charts
description: This is just a placeholder chart that contains a list of system charts required by the llmos-operator.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"
dependencies:
  - name: kuberay-operator
    version: "1.2.1"
    repository: "https://ray-project.github.io/kuberay-helm"
    tags:
      - ml-framework
      - ray.io
  - name: gpu-operator
    version: "v24.6.2"
    repository: "https://helm.ngc.nvidia.com/nvidia"
    tags:
      - gpu-operator
      - nvidia
  - name: rook-ceph
    version: v1.15.2
    repository: https://charts.rook.io/release
    tags:
      - rook
      - ceph
  - name: rook-ceph-cluster
    version: v1.15.2
    repository: https://charts.rook.io/release
    tags:
      - rook
      - ceph-cluster
  - name: redis
    version: 19.6.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - redis
  - name: system-upgrade-controller
    version: 0.1.0
    repository: file://dependency_charts/system-upgrade-controller
    condition: suc.enabled
    tags:
      - system-upgrade
  - name: snapshot-controller
    version: 0.1.0
    repository: file://dependency_charts/snapshot-controller
    tags:
      - csi-snapshotter
